#! /bin/sh

# Numpad
# 1  KP_End
# 2  KP_Down
# 3  KP_Next
# 4  KP_Left
# 5  KP_Begin
# 6  KP_Right
# 7  KP_Home
# 8  KP_Up
# 9  KP_Prior
# 0  KP_Insert

# Mouse
# button1	Left Click
# button2	Middle Click
# button3	Right Click
# button4	Scroll Up
# button5	Scroll Down
# button6	Scroll Left
# button7	Scroll Right
# button8	Back
# button9	Forward

# terminal emulator
super + {_,shift + } Return
	{kitty, bspc node -i}

# program launcher
super + {d,r}
	rofi -modi drun,run -show drun

# program launcher
super + Tab
	rofi -modi window -show window

# file explorer
super + e
	dolphin

# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd

# quit/restart bspwm
super + alt + {q,r}
	bspc {quit,wm -r}

# close and kill
alt + {_,shift + }F4
	bspc node -{c,k}

# alternate between the tiled and monocle layout
super + m
	bspc desktop -l next

# set the window state
super + {t,shift + t,s,f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# set the window fullscreen
alt + enter
	bspc node -t fullscreen

# toggle between floating and tiled
super + {_,shift +} space
	bspc node {focused -t \~floating,-g sticky}

# set the node flags
super + ctrl + {m,x,y,z}
	bspc node -g {marked,locked,sticky,private}

# alt-tab (ish)
alt + {_,shift + ,ctrl +}Tab
	bspc desktop -f {last,prev.local,next.local}

# focus settings for the left monitor
super {_,shift + }KP_{End,Left,Home}
	{~/.local/bin/bspc-left-monitor,bspc node -d} {1,4,7}

# focus or send to the middle monitor
super + {_,shift + }KP_{Down,Begin,Up}
	bspc {desktop -f,node -d} {2,5,8}

# focus or send to the right monitor
super + {_,shift + }KP_{Next,Right,Prior}
	{~/.local/bin/bspc-right-monitor,bspc node -d} {3,6,9}

# Focus desktop by index on current monitor
super + {_,shift + }{1-3}
	bspc {desktop -f,node -d} focused:'^{1-3}'

# Re-focus main screens
super + KP_Insert
	~/.local/bin/bspc-left-monitor 1; \
	bspc desktop -f 2; \
	~/.local/bin/bspc-right-monitor 3

# Re-focus main screens
super + KP_Delete
	~/.local/bin/bspc-left-monitor 7; \
	bspc desktop -f 8; \
	~/.local/bin/bspc-right-monitor 9

# expand a window by moving its left and right sides outward
super + button4
	bspc node -z right 10 0 left 10 0

# contract a window by moving its left and right sides inward
super + button5
	bspc node -z right -10 0 left -10 0

# expand a window by moving its top and bottom sides outward
super + alt + button4
	bspc node -z top 0 10 bottom 0 10

# contract a window by moving its top and bottom sides inward
super + alt + button5
	bspc node -z top 0 -10 bottom 0 -10

# media keys
XF86AudioRaiseVolume
	pactl set-sink-volume @DEFAULT_SINK@ +5%

XF86AudioLowerVolume
	pactl set-sink-volume @DEFAULT_SINK@ -5%

XF86AudioMute
	pactl set-sink-mute @DEFAULT_SINK@ toggle

XF86AudioMicMute
	pactl set-source-mute @DEFAULT_SOURCE@ toggle

XF86Audio{Play,Prev,Next,Stop}
	mpc -q {toggle,cdprev,next,stop}

# screenshots
{_,shift + }Print
	screenshot-scrot {all,selection}