#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-A-0       -d 1 4 7 # Left
bspc monitor DisplayPort-1  -d 2 5 8 # Middle
bspc monitor DisplayPort-2  -d 3 6 9 # Right

bspc config border_width        0
bspc config window_gap          10

bspc config -m DisplayPort-2    top_padding 0

bspc config split_ratio         0.5
bspc config borderless_monocle  false
bspc config gapless_monocle     false

# Left monitor
bspc rule -a TelegramDesktop        monitor=HDMI-A-0 desktop=1 state=pseudo_tiled split_dir=east sticky=on split_ratio=0.225
bspc rule -a discord                monitor=HDMI-A-0 desktop=1 

# Middle monitor
bspc rule -a code-oss               monitor=DisplayPort-1 desktop=2
bspc rule -a Steam                  monitor=DisplayPort-1 desktop=5

# Right monitor 
bspc rule -a Google-chrome          monitor=DisplayPort-2 desktop=3
bspc rule -a deluge                 monitor=DisplayPort-2 desktop=6

# Multi monitor
bspc rule -a xfreerdp               state=floating layer=below private=on sticky=on

# Non specific
bspc rule -a feh                    state=floating center=on
bspc rule -a dolphin                state=floating center=on
bspc rule -a Viewnior               state=floating center=on
bspc rule -a mpv                    state=floating center=on

# External rules
bspc config external_rules_command  ~/.config/bspwm/external_rules

wmname LG3D

bootstrap &